source 'https://rubygems.org'

gem 'travis'
gem 'sinatra', '>= 1.4.5'
gem 'sinatra-flash', '>= 0.3.0'
gem 'sinatra-contrib', '>= 1.4.2'
gem 'shotgun', '>= 0.9'
gem 'zurb-foundation'
gem 'compass'
gem 'rake'
gem 'pony'
gem 'newrelic_rpm'
gem 'faker'
gem 'uuid'
