source 'https://rubygems.org'

gem 'travis', '>= 1.7.4'
gem 'sinatra'
gem 'sinatra-flash'
gem 'sinatra-contrib'
gem 'shotgun'
gem 'zurb-foundation'
gem 'compass', '>= 1.0.1'
gem 'rake'
gem 'pony'
gem 'newrelic_rpm'
gem 'faker'
gem 'uuid'
